package com.fjs.banhangonline.model;
// Generated 2018/05/29 14:49:36 by Hibernate Tools 5.2.8.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * User generated by hbm2java
 */
@Entity
@Table(name = "user", catalog = "banhangonline")
public class User implements java.io.Serializable {

	private Integer id;
	private String usercode;
	private String username;
	private String password;
	private String email;
	private Integer userrole;
	private Integer status;

	public User() {
	}

	public User(String usercode, String username, String password, String email) {
		this.usercode = usercode;
		this.username = username;
		this.password = password;
		this.email = email;
	}

	public User(String usercode, String username, String password, String email, Integer userrole, Integer status) {
		this.usercode = usercode;
		this.username = username;
		this.password = password;
		this.email = email;
		this.userrole = userrole;
		this.status = status;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)

	@Column(name = "id", unique = true, nullable = false)
	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	@Column(name = "usercode", nullable = false, length = 45)
	public String getUsercode() {
		return this.usercode;
	}

	public void setUsercode(String usercode) {
		this.usercode = usercode;
	}

	@Column(name = "username", nullable = false)
	public String getUsername() {
		return this.username;
	}

	public void setUsername(String username) {
		this.username = username;
	}

	@Column(name = "password", nullable = false, length = 45)
	public String getPassword() {
		return this.password;
	}

	public void setPassword(String password) {
		this.password = password;
	}

	@Column(name = "email", nullable = false, length = 45)
	public String getEmail() {
		return this.email;
	}

	public void setEmail(String email) {
		this.email = email;
	}

	@Column(name = "userrole")
	public Integer getUserrole() {
		return this.userrole;
	}

	public void setUserrole(Integer userrole) {
		this.userrole = userrole;
	}

	@Column(name = "status")
	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

}
